import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/ui/Components/SideBar";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Halal Media",
  description: "Generated by create next app",
};
function ErrorBoundary({ children }) {
  try {
    return children;
  } catch (error) {
    console.error(error);
    return <div>Error loading sidebar</div>;
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={geistSans.variable}>
    <body>
      <SidebarProvider>
      <div className="md:w-1/4 lg:w-1/5 hidden md:inline">
            <AppSidebar />
          </div>
        <main>
        <div className="md:hidden p-4">
            <SidebarTrigger />
          </div>
          {children}
        </main>
      </SidebarProvider>
    </body>
  </html>
  );
}
